export const data = {
  presidents: [
    `1952 - Earl DeMotte`,
    `1953 - Ethel Hodges`,
    `1954 - Frank Hanshaw`,
    `1955 - John Whalen`,
    `1956 - Constance Currier`,
    `1957 - John Whalen`,
    `1958 - Constance Currier`,
    `1959 - Charles Rickard`,
    `1960 - Ed Lemon`,
    `1961 - Virginia Bizzell`,
    `1962 - Norman Vrana`,
    `1963 - Joseph "Skeef"Hodgson`,
    `1964 - Barbara Warner`,
    `1965 - Lois McManus`,
    `1966-1967 - Ernest Von Borstel`,
    `1968 - Byron McCalmon`,
    `1969 - Richard Ledford`,
    `1970 - Herbert Schryver`,
    `1971 - Lamartine Hood`,
    `1972 - Ed Hartz`,
    `1973 - Reuben Shapley`,
    `1974 - Marie King`,
    `1975 - Bill House`,
    `1976-1977 - Bill Albern`,
    `1978 - David Donner`,
    `1979 - Betty House`,
    `1980 - Daniel Blumkin`,
    `1981 - Stu Berg`,
    `1982 - Tom Marker/Ross Welch`,
    `1983 - Barry Cooper`,
    `1984 - Peter Littman`,
    `1985-1986 - Pat Haugen`,
    `1987-1988 - Tom Sims`,
    `1989-1991 - Marc Walker`,
    `1992-1993 - Tony Bretscher`,
    `1994 - Joe Lalley`,
    `1995-1996 - Glenn Gray`,
    `1997-1999 - Paul Kneeland`,
    `2000-2002 - Owen Raymond`,
    `2003-2005 - Doug Long`,
    `2006-Present - Christine Beacraft`,
  ],

  harris: [
    `1990 - Dodie Harris, awarded posthumously`,
    `1991 - Marc Walker, Bill Brown`,
    `1992 - Jan Shay`,
    `1993 - Mary Helen Cathles`,
    `1994 - Tony and Janice Bretscher, Barb Batley`,
    `1995 - Joe Lalley, Dave Schlesinger, Mike Murphy`,
    `1996 - Anne Kendall Casella`,
    `1997 - Bill House`,
    `1998 - Mary Royer, Susan Lang, Tom Schneider`,
    `1999 - Bruce Howlett`,
    `2000 - Lynne Mellinger`,
    `2001 - Doug Long and Glen Howser`,
    `2002 - Marcy Schaeffer`,
    `2003 - Owen Raymond, Glenn Henderson, Alex Burdick`,
  ],

  lake: [
    `1993 - painting the exterior of the community center`,
    `1994 - a bike rack at the center and materials needed for the nature trail`,
    `1995 - the endowment was used as seed money for the Harris Family Skating Rink Fund for the facility that was built on East Lake Drive in Ithaca`,
    `1996 - a kiosk to display and store interpretive guides for the nature trail`,
    `1997 - repair of the playground and replacement of crushed stone in the driveway`,
    `1998 - lighting for the skating rink; surplus funds were to be used to offset the cost of brush hogging the rink`,
    `1999 - replacement of plantings in front of the Community Center.The original plantings were overgrown and had been victimized by deer.The plantings are in memory of A.W.Dimock.`,
    `2000 - a new carpet and mats for the community center`,
    `2001 - four new picnic tables for the pavilion`,
    `2002 - a roof over the new barbecue pit.`,
  ],

  slides: [
    {
      name: `The Community Center`,
      number: 1,
      active: true,
    },
    {
      name: `Geographical Aspects: What is Ellis Hollow?`,
      number: 2,
      active: false,
    },
    {
      name: `Native Americans`,
      number: 3,
      active: false,
    },
    {
      name: `Early Pioneers: John and Peleg Ellis`,
      number: 4,
      active: false,
    },
    {
      name: `The New York Military Tract`,
      number: 5,
      active: false,
    },
    {
      name: `The Village of Ellis`,
      number: 6,
      active: false,
    },
    {
      name: `Early Schools`,
      number: 7,
      active: false,
    },
    {
      name: `The Church`,
      number: 8,
      active: false,
    },
    {
      name: `Century Houses`,
      number: 9,
      active: false,
    },
    {
      name: `The Community Center`,
      number: 10,
      active: false,
    },
    {
      name: `Past Community Center Presidents`,
      number: 11,
      active: false,
    },
    {
      name: `Notable Community Members`,
      number: 12,
      active: false,
    },
  ],
}